name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build containers
      run:  docker-compose up --build -d

    - name: Run the tests
      run: docker-compose run users python manage.py test

    - name: Run linter
      run:  docker-compose run users flake8 project
    
    - name: Stop Running containers
      run: docker-compose down
