name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build users container
      run:  docker-compose -f docker-compose-prod.yml build users
    
    - name: Build users-db container
      run:  docker-compose -f docker-compose-prod.yml build users-db
    
    - name: Build nginx container
      run:  docker-compose -f docker-compose-prod.yml build nginx
    
    - name: Run the container
      run: docker-compose -f docker-compose-prod.yml up -d

    - name: Test the builds
      run:  docker-compose run users python manage.py test
